### ISSUE TITLE
Watchlist item only added upon Watchlistarr restart

### ISSUE THREAD

**Issue by hstamas** [nylonee/watchlistarr#182] opened 2024-08-26 20:37 UTC
Got Watchlistarr up and running via Docker on an M1 Mac. If I add a movie to my Plex watchlist, Radarr will only pick it up if I stop and restart the Watchlistarr Docker container.

I am extremely new to Docker so maybe I dont have something set correctly?

**Comment by tiredjohn** [comment] 2024-08-27 12:03
Same issue here, also running on docker – but the refresh has fallen back to every 19 minutes, or whenever I restart the container. Seems like REFRESH_INTERVAL_SECONDS isn't being respected. (I'm using Plex Pass)

**Comment by Redryan243** [comment] 2024-08-27 16:12
Same issue here. My logs show it defaulting to a 60 second interval, even though my config specifies 10 seconds. It is working at the 60 second at least for me.

**Comment by hstamas** [comment] 2024-08-27 16:58
Glad it not just me! I dont quite know of to set up the config file so I am just using what ever defaults. I do have a Plexpass and I see in the logs that it is recognized as such.

**Comment by tiredjohn** [comment] 2024-08-28 10:11
I've looked into this and the issue seems to be that Plex has added server-side caching to their RSS feeds. The refresh interval is working as intended, but the server cache means that it keeps fetching the same data regardless of the update frequency. 

I've made a change and submitted a PR to append a random 10 character parameter to the RSS URL each time it's used, which fixes it for me.

**Comment by hstamas** [comment] 2024-08-29 13:23
Thanks for the fork @tiredjohn while we wait for this fix to be integrated. 

I am geting a warning in Docker when I run your fork concerning arrm64? when it runs, it seems to work but I have incredibly high CPU usage (151%). 

Again I am on an M1 Mac.

Any ideas?

**Comment by strangedesign13** [comment] 2024-08-29 21:30
@tiredjohn thanks for this! Totally solved my problem!

**Comment by hstamas** [comment] 2024-08-30 11:57
@tiredjohn any idea why I am seeing this warning when I pull your image? Im on a Mac M1.

"AMD64 - Image may have poor performance if run via emulation"

![Screen Shot 2024-08-30 at 7 51 35 AM](https://github.com/user-attachments/assets/885674da-381c-4b52-a476-5eaeb88d85f3)

**Comment by tiredjohn** [comment] 2024-08-30 18:58
> @tiredjohn any idea why I am seeing this warning when I pull your image? Im on a Mac M1.

I've added an arm64 build for you, try pulling it again.

**Comment by hstamas** [comment] 2024-08-31 13:58
Perfect @tiredjohn , thank you!

Probably doesn't come as a surprise to anyone that I am a complete Docker noob but this is forcing me to learn the basics at least!

Question. If I ran the build command that nylonee has listed at the bottom of his Github page (docker build -t nylonee/watchlistarr:latest -f docker/Dockerfile ), would that have accomplished the same thing? Given me an image that was comparable with arm64 machines (my Mac M1)?

**Comment by tiredjohn** [comment] 2024-09-01 06:40
@hstamas My version is tiredjohn/watchlistarr, so "docker pull tiredjohn/watchlistarr:latest" should do it for you.

**Comment by Abolfazl** [comment] 2024-10-04 02:01
@tiredjohn I setup you version of watchlistarr and it fixed the sync issue. However I am having an issue where I keep getting an error that `[WARNING] Your app's responsiveness to a new asynchronous event (such as a new connection, an upstream response, or a timer) was in excess of 100 milliseconds. Your CPU is probably starving. Consider increasing the granularity of your delays or adding more cedes. This may also be a sign that you are unintentionally running blocking I/O operations (such as File or InetAddress) without the blocking combinator.`. I think the original nylonee/watchlistarr image was producing this error too

**Comment by nylonee** [comment] 2024-10-16 21:19
Thanks for your help @tiredjohn and for the debugging all, I've pushed a fix (#190) to beta and will release it to the main docker tag soon

**Closed by nylonee** 2024-10-16 21:19 UTC
